# The logging configuration. On a real server this will be a file url. e.g. file://{{ mujina_dir }}/logback.xml
logging:
  config: classpath:logback.xml

server:
  # The port to where this Spring Boot application listens to. e.g. http://localhost:{{ springapp_tcpport }}
  port: 9090
  # The context path of the server. You can skip this value in the overriding application.yml on the classpath
  contextPath:
  session:
    # 8 hours before we time-out
    timeout: 28800
    cookie:
      secure: false

sp:
  # base url
  #base_url: http://10.120.116.169:9090
  base_url: http://localhost:9090
  # Entity ID of the SP
  #entity_id: lenovosp123
  entity_id: localhostlenovo
  # Private key used to sign the SAML response
  #private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQRsCf6qU0DYkoFIJUhNlMxJFKMPsEvK+u3rcaBIZcyWX4Cv5OU3xtcCAg6mqRwMRFYFDNdGgR0XLTaHAOcJpR7cXYnYc0Wa6Kh8KSstgZrCl+WdqCtuUS6bMrrAdSq6HpoAPwo1JyOqyC9ccRZ9ysjhYdWQS1ELSjUHjEuxxRoEgwKfrF7kxbo89dixQ7oF9E9CgeWtftJfMtDxGtMhmtaIurHjjcfOPWR8TND0b1Lp1pLkzPn6GdI2aRWqV3tNsljKoXP9omDInhP9xrzoLiXISbekfnLrfFQW+rmylCBiu6ZqKv0weg1V6b7B6rAyV3nIcXInLuKXSlQx0nnPOdAgMBAAECggEAOrAlKSqyYIeL5XpZ+zzwCly9X/2LThtpGcpyJ+esgMrTa+CVJjcKMcBNnVjQrL93zuDEBBDQHm05gO7F3JvIMFviyxYgehTnROvaXQH+OMW1b4AcPYcR55Foxl6UNaxdVHqdgZpT6hI0eDaPYI02tnzXKG/kDq1laTuMvErJQQp6Cd611yyAhBvpX1ibpAYvex10sfTkj0GRKmOrGqwVXibN29szaRei7Xeg/RStdVBgrYJoR5/4++dkGapa27oRdOh4VJUChRfXuJtH6pyxC7uay1fMRcmo2u6NcWAT6qMOvxLcuesnNFrbSlPoZaxWNiZRX/SVqeieyRAA0WS7IQKBgQDoywh4DkdL+SPrkA/sB0rOQF3kJjlzWibk9OM17In1P+obQk37kSRYKfBvsk48VWdG1fN33Up05Pxe+f36F//AZ8mp7uTmBtd6CAoR/005WxwkCSihF6LaDiB3VtxlpcfRA/TUZ10PMud43w0AeG30AG0KpCokfIiY87OpyTjJWQKBgQDlCgsgZ9rL3Wm7FbEDZ4f2uTB5rlT0Vz80paV0OOJdUQECrZW1PjemQpqIJocr8yoNupkrZKPSi4mbNoMFF1wXIydOjLq6iQ6KWIKRdsvmeXL++tWg6TiD8nDpBxuKzjRhwMcQN2lakb/SusoXnmG8qq12PCFUvpbhoZRqRPWv5QKBgQC8jUasxxPka0U21RawXC+w4t2pn3RFBC4goGEwGgibxkr+DTRQoHzJlB6Uud04bQwbicuLuIdIKvhmjSGzYaDa3LWwmDh6P+xjgQN3FEweOreOUITCBfz3lR2iy430HtS7bPLu31G2r8pgUnmbee/FBFtNlS41I1EYYbuRt9Pw8QKBgD6aPSpRWKtqTHD3X9e3X6FfQtGvhcb3Ze5E7HFU7wJklqsduRK9+8X05HocVcv8fd0cyKrkqiZtP2JuRueIWAJ2+FJvAsbjmVbVFHMgDmFjhrwM4YFG3cyq4pO+/pc0/3pMj9xt2N0Jg23c4koMX1iLKjhr/QxFv8XSPVfCm4jFAoGALfejdx4PpFgTWpbm5ZWRxukhZRhmfCIAWifYeJbsGTB5y7bheVxKmTpP9mKEqGL+gh3cLVPcZ557HWpc4d6NetdyrHffEhWULh4NWYDKC5BRCr9HjLKydBUQUMCFeJs3XZQTtN+CZORcuaI2ISH2QvfYki9ns4ujeH8OjzfHpvI=
  private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5+HT7Xj3qa+k2XR4dAdBL0LYEFW1F8bb0dMRIPwyvOYZid/kTg6U95AoNkvaE6z4dbvdvPaPPQWEk3yl39WL/tv7ZKA8aKGFQbGNgs3hUjL9ZcruSWE/C1N556CVe7djIeMnGORQSY4QD92W/nGw+PJ9+xlTg+l7IQ2n4ZYqjyXcUqdwvWPm0N0aqpJofom27hcAFCgn8wPor+YsFgqfoiWQDpgkg4hPmDWhR6lao5CBHlpsQ6p76AbJkjGia4txPJleHEbMa7/+bzowD8iPrRh+UiZI2mimnJ4+y1glZ6obxvf7MJvcKxpl/WKZReKo2TbtOwUJizFPRRgYFc9tJAgMBAAECggEACvQLT9LZKrl4Xu9VGrhEoHKGhe8NJJV8BSHrfaXZBWkJ9TrDvNaAIQkRXoNNab7BRdKHWFH1F/vt0NIkCyC02ALbN8cYPJ4sPSRlJgjsCW7Qxl/vlEsHR55qDBwUN2ci4YvbtoUeHYcm+2TS5Vo9Nd00N69OyIF2m6z8zNiONd9J8Jf6PimO09Sjtv2UAS4Vkv6M88JT1/rAKz49nCLvWAOMSsPXN4cGwNoJkJR5eKlP3j/zydzPl/T41TxIK94tfNrzfoks9W3zb6iUykF4LPvxIi9nV8DGrIeoZNJoQpdj8oBXsDvFeVndHJniS4BFgT81BYYDjPOWxbWj/ADpQQKBgQD3UqnpyqBJckiu3+ndz8FNvT9NpsfER7h/4w6wQbKlLpZDZFj39NV3uSuSe5FYRNEdI5M8j1+/G1Kmvr6eKEo36CbsOU74G7Uc6Deu/pU/F67Qx4vZk4tvXTqq5E+NxzN8uewnQa4eJW+Cjk8IeQVwcQrym5TnS60kuXnx6molbQKBgQDAfsFqsN8W1KuBiFKLlPrws3TgCwHVmpkMUxqMnQt4DVKcF3dhmGbrxNaIdz2Ih3AXmMAd6+HKmJxsVI1/oJmdCdqFd+WELO5tEtNRjuVatzKf1j2Nt3oB1D/d4KTrMR0BmnyKTgXdmLd9cYCJl4zkP4KRNPYqnJ4CLHZHdjyPzQKBgBTVyOyiHkixsP/SazA9fUpgRAH1p+SYKinT5fvhPPx/ZTc+L+SLoqQYXFxVvpPSEE/FHHVAms9NrPPRI9vNBxuYmhbSaR2rr+FEitRaLBaJlzeNZ/GnZVq3XubgnvcRrfu26fcQqGtvueoktPHAyD2FuGdhxfSKQobSfTxtBA4tAoGBAJ//e7K7iuKGKHvFHJ9KWH4DG60xWPf7xSSaWqHv0t2ZbUWyt5bWPw3PEWZifjHiKUhjvaPhMU7dJH9ilC42BhiiXRC9BHelhRQCJsVOmdKaHSj/wS/vBilJC0DX/RxEOVDg4I1wpq12x2UsF2PGJOR+6X7aX5YxkaBK5pEldNctAoGAM9gjMOqZ4qnWJvsbqUZvwj8bFFiV2I6Mwst9/x+p2F/RCFyOve6Q25zTSmNfnOBYnLWmOgPoe8FHiynFgeHGj4Uo31YEettMdF/xMnUHO0Nd1YfjHssUQep0bYq03pjv/pMvC/Ump5467jzm9P5Wq/TncRm4teQFU7HzhG+roZc=
  # Public certificate to verify the signature of the SAML response
  #certificate: MIIDEzCCAfugAwIBAgIJAKoK/heBjcOYMA0GCSqGSIb3DQEBBQUAMCAxHjAcBgNVBAoMFU9yZ2FuaXphdGlvbiwgQ049T0lEQzAeFw0xNTExMTExMDEyMTVaFw0yNTExMTAxMDEyMTVaMCAxHjAcBgNVBAoMFU9yZ2FuaXphdGlvbiwgQ049T0lEQzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANBGwJ/qpTQNiSgUglSE2UzEkUow+wS8r67etxoEhlzJZfgK/k5TfG1wICDqapHAxEVgUM10aBHRctNocA5wmlHtxdidhzRZroqHwpKy2BmsKX5Z2oK25RLpsyusB1KroemgA/CjUnI6rIL1xxFn3KyOFh1ZBLUQtKNQeMS7HFGgSDAp+sXuTFujz12LFDugX0T0KB5a1+0l8y0PEa0yGa1oi6seONx849ZHxM0PRvUunWkuTM+foZ0jZpFapXe02yWMqhc/2iYMieE/3GvOguJchJt6R+cut8VBb6ubKUIGK7pmoq/TB6DVXpvsHqsDJXechxcicu4pdKVDHSec850CAwEAAaNQME4wHQYDVR0OBBYEFK7RqjoodSYVXGTVEdLf3kJflP/sMB8GA1UdIwQYMBaAFK7RqjoodSYVXGTVEdLf3kJflP/sMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBADNZkxlFXh4F45muCbnQd+WmaXlGvb9tkUyAIxVL8AIu8J18F420vpnGpoUAE+Hy3evBmp2nkrFAgmr055fAjpHeZFgDZBAPCwYd3TNMDeSyMta3Ka+oS7GRFDePkMEm+kH4/rITNKUF1sOvWBTSowk9TudEDyFqgGntcdu/l/zRxvx33y3LMG5USD0x4X4IKjRrRN1BbcKgi8dq10C3jdqNancTuPoqT3WWzRvVtB/q34B7F74/6JzgEoOCEHufBMp4ZFu54P0yEGtWfTwTzuoZobrChVVBt4w/XZagrRtUCDNwRpHNbpjxYudbqLqpi1MQpV9oht/BpTHVJG2i0ro=
  certificate: MIICyjCCAbICCQCBSD9UXxmspTANBgkqhkiG9w0BAQsFADAnMSUwIwYDVQQKDBxPcmdhbml6YXRpb24sIENOPUxlbm92b1NQMTIzMB4XDTE5MDUxNDA4MTQzNVoXDTI5MDUxMzA4MTQzNVowJzElMCMGA1UECgwcT3JnYW5pemF0aW9uLCBDTj1MZW5vdm9TUDEyMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALn4dPtePepr6TZdHh0B0EvQtgQVbUXxtvR0xEg/DK85hmJ3+RODpT3kCg2S9oTrPh1u9289o89BYSTfKXf1Yv+2/tkoDxooYVBsY2CzeFSMv1lyu5JYT8LU3nnoJV7t2Mh4ycY5FBJjhAP3Zb+cbD48n37GVOD6XshDafhliqPJdxSp3C9Y+bQ3Rqqkmh+ibbuFwAUKCfzA+iv5iwWCp+iJZAOmCSDiE+YNaFHqVqjkIEeWmxDqnvoBsmSMaJri3E8mV4cRsxrv/5vOjAPyI+tGH5SJkjaaKacnj7LWCVnqhvG9/swm9wrGmX9YplF4qjZNu07BQmLMU9FGBgVz20kCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEARh28zAQw0shpnbq5oEIMSlsLxtF7iAEZCSzrL9rqRCXIMzzhFjgc74GOXaoIxdbDqhBb1TVVbT7Em+pFIMxuQIBCggelCZK9dEw/OBxy81ocI3b0EmCaB/6xa6azlgqyT+Oq7NnYjrURVQKMD2zHSM8u7x8evGvvXkS2Ltv09YBSE9x8k3Emf+8bbbVKBaL1y54VgTFjMk+ino1ygHlCUO5rPCOrwcojRRgcbA7L+pKm+leTDJ3asDGeLe1hUj+1mYz6VNKN4HY+m0po69HEzKzdeQCpDtANqsv2e3qkb+DMULsMeJtvkHk+VFJQiTV0DOTBd0dAuA+1V4JbCnCccA==
  # Passphrase of the keystore
  passphrase: secret
  # Resource URL for the idp metadata
  #idp_metadata_url: classpath:metadata/mujina.local.idp.metadata.xml
  idp_metadata_url: classpath:metadata/liferay.idp.xml
  # SingleSignOnServiceLocation
  #single_sign_on_service_location: http://localhost:8080/SingleSignOnService
  single_sign_on_service_location: http://10.251.65.247:8080/c/portal/saml/sso
  # ACS location
  acs_location_path: /saml/SSO
  # Protocol binding
  protocol_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
  # Do we sign the authnRequest
  needs_signing: true
  # Are endpoints compared. If so then pay notice to the base_url when behind a load balancer
  compare_endpoints: true


spring:
  velocity:
    check-template-location: False

# We disable all endpoints except health for the load-balancer and info for git information.
endpoints:
  enabled: false
  jmx:
    enabled: false
  health:
    enabled: true
  info:
    enabled: true

# used by the git plugin

